use("Project")

//Users
db.users.insertOne({user_id:"user1",username:"user1_username",email:"user1@example.com",password:"user1_password",profile_picture:"user1.jpg",last_active:"2023-20-10",registration_date:"2023-01-01",following:["user2","user3"],followers:["user2","user3"]});
db.users.insertMany([{user_id:"user2",username:"user2_username",email:"user2@example.com",password:"user2_password",profile_picture:"user2.jpg",last_active:"2010-20-10",registration_date:"2023-01-02",following:["user1","user3"],followers:["user1","user3"]},{user_id:"user3",username:"user3_username",email:"user3@example.com",password:"user3_password",profile_picture:"user3.jpg",last_active:"2010-20-10",registration_date:"2023-01-03",following:["user1","user2"],followers:["user1","user2"]},{user_id:"user4",username:"user4_username",email:"user4@example.com",password:"user4_password",profile_picture:"user4.jpg",last_active:"2010-20-10",registration_date:"2023-01-04",following:["user1","user2","user3"],followers:["user1","user2","user3"]}]);

//Posts
db.posts.insertOne({post_id:"post20",user_id:"user1",publish_date:"2023-01-05",URL:"post1.jpg",type:"image",title:"Post1",description:"Thisisthefirstpost.",comments:[{comment_text:"Nicepost!",user_id:"user2",timestamp:"2023-01-06"}],likes:{user_ids_who_liked:["user2"],like_dates:["2023-01-06"]}});
db.posts.insertMany([{post_id:"post1",user_id:"user1",publish_date:"2023-01-05",URL:"post1.jpg",type:"image",title:"Post1",description:"Thisisthefirstpost.",comments:[{comment_text:"Nicepost!",user_id:"user2",timestamp:"2023-01-06"}],likes:{user_ids_who_liked:["user2"],like_dates:["2023-01-06"]}},{post_id:"post2",user_id:"user2",publish_date:"2023-01-07",URL:"post2.jpg",type:"image",title:"Post2",description:"Anotherpost.",comments:[],likes:{user_ids_who_liked:[],like_dates:[]}},{post_id:"post3",user_id:"user3",publish_date:"2023-01-08",URL:"post3.jpg",type:"text",title:"TextPost",description:"Thisisatextpost.",comments:[{comment_text:"Interesting!",user_id:"user1",timestamp:"2023-01-09"},{comment_text:"Iagree!",user_id:"user2",timestamp:"2023-01-10"}],likes:{user_ids_who_liked:["user1","user2"],like_dates:["2023-01-09","2023-01-10"]}},{post_id:"post4",user_id:"user1",publish_date:"2023-01-09",URL:"post4.jpg",type:"video",title:"VideoPost",description:"Checkoutthisvideo!",comments:[{comment_text:"Amazingvideo!",user_id:"user3",timestamp:"2023-01-10"}],likes:{user_ids_who_liked:["user3"],like_dates:["2023-01-10"]}}]);

//Groups
db.groups.insertOne({group_id:"group1",group_name:"Group1",description:"Thisisgroup1",admin_id:"user1",members:["user1","user2"],created_date:"2023-01-04",posts:["post1"]});
db.groups.insertMany([{group_id:"group2",group_name:"Group2",description:"Thisisgroup2",admin_id:"user2",members:["user2","user3"],created_date:"2023-01-05",posts:["post2","post3"]},{group_id:"group3",group_name:"Group3",description:"Thisisgroup3",admin_id:"user3",members:["user1","user3"],created_date:"2023-01-06",posts:["post4"]}]);

//Messages 
db.messages.insertOne({sender:"user1",receiver:"user2",message_content:"Hello,user2!",timestamp:"2023-01-03",message_status:"sent"});
db.messages.insertMany([{sender:"user1",receiver:"user3",message_content:"Hey,user3!Howareyou?",timestamp:"2023-01-04",message_status:"sent"},{sender:"user3",receiver:"user1",message_content:"Hi,user1!I'mdoingwell,thanks!",timestamp:"2023-01-04",message_status:"sent"},{sender:"user2",receiver:"user3",message_content:"Hello,user3!Anyplansfortheweekend?",timestamp:"2023-01-05",message_status:"sent"},{sender:"user3",receiver:"user2",message_content:"Notsureyet!Maybeamovienight.Howaboutyou?",timestamp:"2023-01-05",message_status:"sent"}]);